#!/usr/bin/env ruby
# -*- mode: ruby -*-

require 'populus'

mode = ARGV[0]
setting = ARGV[1]

case mode
when 'accept'
  Populus.eval_setting setting

  data = STDIN.read
  Populus::Do.accept data
when 'watch'
  count = (ARGV[2] || 1).to_i
  Populus::Daemon.run(setting, count)
else
  Populus.logger.error "Unknown arg: #{mode}"
  exit 127
end

exit 0
